import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  headerArea: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  mainBox: {
    flex: 1,
    padding: 16,
    backgroundColor: "#fff",
    width: "100%",
  },
  themeStyle: {
    maxHeight: 400,
    backgroundColor: "#f5f5f5",
    elevation: 2,
    borderRadius: 8,
    marginVertical: 8,
  },
  themeStyleAlt: {
    maxHeight: 400,
    backgroundColor: "#f8f8f8",
    elevation: 1,
    borderRadius: 8,
    marginTop: 16,
  },
  itemBox: {
    padding: 16,
    marginVertical: 8,
    backgroundColor: "#ffffff",
    borderRadius: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  foodTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#333333",
    marginVertical: 4,
  },
  detailText: {
    fontSize: 16,
    color: "#666666",
    marginVertical: 2,
  },
  mainHeading: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#333333",
    marginBottom: 16,
  },
  subDetails: {
    fontSize: 14,
    color: "#666666",
    textAlign: "center",
  },
  subHeading: {
    fontSize: 20,
    fontWeight: "600",
    color: "#333333",
    marginVertical: 8,
  },
  inputWrapper: {
    alignItems: "center",
    width: "100%",
    backgroundColor: "#ffffff",
    padding: 16,
    borderRadius: 8,
    elevation: 2,
  },
  textField: {
    width: "100%",
    height: 40,
    backgroundColor: "#f5f5f5",
    paddingHorizontal: 12,
    marginVertical: 8,
    borderRadius: 4,
    fontSize: 16,
    borderColor: "#dddddd",
    borderWidth: 1,
  },
  descriptionField: {
    width: "100%",
    height: 80,
    backgroundColor: "#f5f5f5",
    paddingHorizontal: 12,
    marginVertical: 8,
    borderRadius: 4,
    fontSize: 16,
    borderColor: "#dddddd",
    borderWidth: 1,
    textAlignVertical: "top",
    paddingTop: 8,
  },
  actionButton: {
    backgroundColor: "#007AFF",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginVertical: 8,
    alignItems: "center",
    width: "100%",
  },
  secondaryButton: {
    backgroundColor: "#F0F0F0",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginVertical: 8,
    alignItems: "center",
    width: "100%",
  },
  buttonLabel: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  secondaryButtonLabel: {
    color: "#333333",
    fontSize: 16,
    fontWeight: "600",
  },
  summaryBox: {
    backgroundColor: "#f5f5f5",
    padding: 16,
    borderRadius: 8,
    width: "100%",
    marginVertical: 8,
  },
  summaryLabel: {
    fontSize: 14,
    color: "#666666",
    marginVertical: 2,
  },
  removeButton: {
    backgroundColor: "#FF3B30",
    padding: 12,
    borderRadius: 8,
    marginTop: 8,
    alignItems: "center",
  },
  textContainer: {
    marginBottom: 16,
  },
  averageBox: {
    backgroundColor: "#ffffff",
    borderRadius: 8,
    padding: 16,
    marginVertical: 8,
  },
  removeButtonLabel: {
    color: "#FFFFFF",
    fontWeight: "600",
  },
  titleText: {
    marginVertical: 16,
  },
  imageStyle: {
    height: 200,
    width: "100%",
    borderRadius: 8,
  },
  stickyButton: {
    padding: 16,
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderTopColor: "#dddddd",
  },
});